workflows:
  tests:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
        - pattern: gh-pages
          include: false
      cancel_previous_builds: true
    environment:
      vars:
        XCODE_PROJECT: Maccy.xcodeproj
        XCODE_SCHEME: Maccy
      xcode: 14.2
    scripts:
      - name: Run test 
        script:  xcodebuild test-without-building -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -destination "platform=macOS,arch=arm64"
      - name: Run tests
        script: |
          xcode-project run-tests \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --sdk macosx \
            --test-xcargs "CODE_SIGNING_ALLOWED='no'" \
            --output-dir build/macos/test
        test_report: build/macos/test/*.xml
